# Site
name: "The Product Brief"
description: "in which I discuss ideas to improve or next-step products, write about technical people writing, and ramble about life"
meta_description: "Jekyll template, Medium styled, free for bloggers."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: 
google_analytics: 'UA-46278016-1'
disqus: 'productbrief'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

finalurl: https://productbrief.github.io
root_desc: "The Product Brief"

# Authors
authors:
  ryan:
    name: Ryan Haber
    display_name: Ryan Haber
    gravatar: d0076fb131b9cd1b2b93d5b7bb7c5ae7
    email: ryan.haber@gmail.com
    web: /about-me.html 
    twitter: https://twitter.com/techwriterryan
    description: "I make things clear."

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge